
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { AnalysisCard } from "./analysis-card";
import type { Analysis } from "@/lib/types";
import Link from 'next/link';
import { Button } from "./ui/button";
import { ArrowRight } from "lucide-react";

// Mock data for demonstration purposes
const mockAnalyses: Analysis[] = [
  {
    id: "1",
    decisionQuestion: "Should we invest in expanding to Market X or Market Y?",
    status: "completed",
    completedAt: "2024-07-28T10:00:00Z",
    primaryRecommendation: "Proceed with Market Y based on projected growth.",
    confidenceScore: 88,
  },
  {
    id: "2",
    decisionQuestion: "Optimal resource allocation for Q4 product launch?",
    status: "completed",
    completedAt: "2024-07-25T14:30:00Z",
    primaryRecommendation: "Allocate 60% of budget to digital marketing.",
    confidenceScore: 92,
  },
    {
    id: "3",
    decisionQuestion: "Evaluate risk assessment of new supplier chain.",
    status: "in_progress",
    completedAt: "2024-08-01T18:00:00Z",
    primaryRecommendation: "Pending analysis...",
    confidenceScore: 0,
  },
];


export function RecentAnalyses() {
  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
            <CardTitle>Recent Analyses</CardTitle>
            <CardDescription>Review the latest insights generated by Pollitago.</CardDescription>
        </div>
        <Button asChild variant="ghost" size="sm">
            <Link href="/search">
                View All <ArrowRight className="w-4 h-4 ml-2" />
            </Link>
        </Button>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {mockAnalyses.map((analysis) => (
            <AnalysisCard key={analysis.id} analysis={analysis} />
          ))}
        </div>
      </CardContent>
    </Card>
  )
}
