export default function TermsOfService() {
    return (
      <div className="bg-background text-foreground min-h-screen">
        <div className="container mx-auto px-4 py-16 max-w-3xl">
          <h1 className="text-4xl font-bold font-heading mb-6 metallic-gradient">Terms of Service</h1>
          <div className="prose prose-invert text-foreground/80 space-y-4">
            <p>
              Welcome to Pollitago.ai. By accessing or using our services ("the Service"), you agree to be bound by these Terms of Service ("Terms"). Please read them carefully.
            </p>
            <h2 className="text-2xl font-bold font-heading">1. Use of Service</h2>
            <p>
              The Service provides AI-generated second opinions and insights for informational purposes only. You must be at least 18 years old or the age of majority in your jurisdiction to use the Service. You agree to use our services for lawful and ethical purposes only.
            </p>
            <h2 className="text-2xl font-bold font-heading">2. No Professional Advice</h2>
            <p>
              The advice, opinions, and information provided by Pollitago.ai are generated by an artificial intelligence model and are not a substitute for professional, financial, legal, medical, or any other form of licensed advice. The AI's output may contain errors, inaccuracies, or biases. You should always consult with a qualified human professional for critical decisions.
            </p>
            <h2 className="text-2xl font-bold font-heading">3. User Responsibility</h2>
            <p>
              You are solely responsible for the decisions you make and the actions you take based on the information provided by the Service. Pollitago.ai, its creators, and affiliates are not liable for any outcomes, damages, or losses resulting from your reliance on the Service. Do not input any sensitive, illegal, confidential, or personally identifiable information that you are not authorized to share or that would violate data protection regulations.
            </p>
             <h2 className="text-2xl font-bold font-heading">4. Intellectual Property</h2>
            <p>
              All content on this website, including text, graphics, logos, and the AI models, are the property of Pollitago.com and are protected by intellectual property laws. You may not reproduce, distribute, or create derivative works from the Service without our express written permission.
            </p>
            <h2 className="text-2xl font-bold font-heading">5. Limitation of Liability</h2>
            <p>
              The Service is provided "as is" and "as available" without any warranties of any kind, either express or implied. We do not warrant that the service will be uninterrupted, error-free, or secure. In no event shall Pollitago.ai be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your use of the Service.
            </p>
            <h2 className="text-2xl font-bold font-heading">6. Changes to Terms</h2>
             <p>
              We reserve the right to modify these Terms at any time. We will notify you of any changes by posting the new Terms on this page. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.
            </p>
            <p>
              For questions about these Terms, please contact us at <a href="mailto:legal@pollitago.com" className="text-primary hover:underline">legal@pollitago.com</a>.
            </p>
          </div>
        </div>
      </div>
    );
  }
  
